// flow-typed signature: b75901b0166c62390494468ac46d3fca
// flow-typed version: <<STUB>>/dom-align_v^1.8.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-align' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-align/es/adjustForViewport' {
  declare module.exports: any;
}

declare module 'dom-align/es/align/align' {
  declare module.exports: any;
}

declare module 'dom-align/es/align/alignElement' {
  declare module.exports: any;
}

declare module 'dom-align/es/align/alignPoint' {
  declare module.exports: any;
}

declare module 'dom-align/es/getAlignOffset' {
  declare module.exports: any;
}

declare module 'dom-align/es/getElFuturePos' {
  declare module.exports: any;
}

declare module 'dom-align/es/getOffsetParent' {
  declare module.exports: any;
}

declare module 'dom-align/es/getRegion' {
  declare module.exports: any;
}

declare module 'dom-align/es/getVisibleRectForElement' {
  declare module.exports: any;
}

declare module 'dom-align/es/index' {
  declare module.exports: any;
}

declare module 'dom-align/es/isAncestorFixed' {
  declare module.exports: any;
}

declare module 'dom-align/es/propertyUtils' {
  declare module.exports: any;
}

declare module 'dom-align/es/utils' {
  declare module.exports: any;
}

declare module 'dom-align/lib/adjustForViewport' {
  declare module.exports: any;
}

declare module 'dom-align/lib/align/align' {
  declare module.exports: any;
}

declare module 'dom-align/lib/align/alignElement' {
  declare module.exports: any;
}

declare module 'dom-align/lib/align/alignPoint' {
  declare module.exports: any;
}

declare module 'dom-align/lib/getAlignOffset' {
  declare module.exports: any;
}

declare module 'dom-align/lib/getElFuturePos' {
  declare module.exports: any;
}

declare module 'dom-align/lib/getOffsetParent' {
  declare module.exports: any;
}

declare module 'dom-align/lib/getRegion' {
  declare module.exports: any;
}

declare module 'dom-align/lib/getVisibleRectForElement' {
  declare module.exports: any;
}

declare module 'dom-align/lib/index' {
  declare module.exports: any;
}

declare module 'dom-align/lib/isAncestorFixed' {
  declare module.exports: any;
}

declare module 'dom-align/lib/propertyUtils' {
  declare module.exports: any;
}

declare module 'dom-align/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-align/es/adjustForViewport.js' {
  declare module.exports: $Exports<'dom-align/es/adjustForViewport'>;
}
declare module 'dom-align/es/align/align.js' {
  declare module.exports: $Exports<'dom-align/es/align/align'>;
}
declare module 'dom-align/es/align/alignElement.js' {
  declare module.exports: $Exports<'dom-align/es/align/alignElement'>;
}
declare module 'dom-align/es/align/alignPoint.js' {
  declare module.exports: $Exports<'dom-align/es/align/alignPoint'>;
}
declare module 'dom-align/es/getAlignOffset.js' {
  declare module.exports: $Exports<'dom-align/es/getAlignOffset'>;
}
declare module 'dom-align/es/getElFuturePos.js' {
  declare module.exports: $Exports<'dom-align/es/getElFuturePos'>;
}
declare module 'dom-align/es/getOffsetParent.js' {
  declare module.exports: $Exports<'dom-align/es/getOffsetParent'>;
}
declare module 'dom-align/es/getRegion.js' {
  declare module.exports: $Exports<'dom-align/es/getRegion'>;
}
declare module 'dom-align/es/getVisibleRectForElement.js' {
  declare module.exports: $Exports<'dom-align/es/getVisibleRectForElement'>;
}
declare module 'dom-align/es/index.js' {
  declare module.exports: $Exports<'dom-align/es/index'>;
}
declare module 'dom-align/es/isAncestorFixed.js' {
  declare module.exports: $Exports<'dom-align/es/isAncestorFixed'>;
}
declare module 'dom-align/es/propertyUtils.js' {
  declare module.exports: $Exports<'dom-align/es/propertyUtils'>;
}
declare module 'dom-align/es/utils.js' {
  declare module.exports: $Exports<'dom-align/es/utils'>;
}
declare module 'dom-align/lib/adjustForViewport.js' {
  declare module.exports: $Exports<'dom-align/lib/adjustForViewport'>;
}
declare module 'dom-align/lib/align/align.js' {
  declare module.exports: $Exports<'dom-align/lib/align/align'>;
}
declare module 'dom-align/lib/align/alignElement.js' {
  declare module.exports: $Exports<'dom-align/lib/align/alignElement'>;
}
declare module 'dom-align/lib/align/alignPoint.js' {
  declare module.exports: $Exports<'dom-align/lib/align/alignPoint'>;
}
declare module 'dom-align/lib/getAlignOffset.js' {
  declare module.exports: $Exports<'dom-align/lib/getAlignOffset'>;
}
declare module 'dom-align/lib/getElFuturePos.js' {
  declare module.exports: $Exports<'dom-align/lib/getElFuturePos'>;
}
declare module 'dom-align/lib/getOffsetParent.js' {
  declare module.exports: $Exports<'dom-align/lib/getOffsetParent'>;
}
declare module 'dom-align/lib/getRegion.js' {
  declare module.exports: $Exports<'dom-align/lib/getRegion'>;
}
declare module 'dom-align/lib/getVisibleRectForElement.js' {
  declare module.exports: $Exports<'dom-align/lib/getVisibleRectForElement'>;
}
declare module 'dom-align/lib/index.js' {
  declare module.exports: $Exports<'dom-align/lib/index'>;
}
declare module 'dom-align/lib/isAncestorFixed.js' {
  declare module.exports: $Exports<'dom-align/lib/isAncestorFixed'>;
}
declare module 'dom-align/lib/propertyUtils.js' {
  declare module.exports: $Exports<'dom-align/lib/propertyUtils'>;
}
declare module 'dom-align/lib/utils.js' {
  declare module.exports: $Exports<'dom-align/lib/utils'>;
}
